name: Frontend Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: badminton-app/package-lock.json

      # Install dependencies
      - name: Install dependencies
        run: |
          cd badminton-app
          npm install --legacy-peer-deps

      # Build Angular
      - name: Build Angular
        run: |
          cd badminton-app
          npm run build

      # Upload Web Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: badminton-app/dist/badminton-app
